<?php
namespace NAWebCo\BoxPacker;

use PHPUnit\Framework\TestCase;

class ContainerLevelTest extends TestCase
{

    public function testCreateFromDimensions()
    {
        $container = ContainerLevel::createFromDimensions(3, 2, 1);
        $this->assertInstanceOf(ContainerLevel::class, $container);
    }

    /**
     * @expectedException \InvalidArgumentException
     */
    public function testConstructWithInvalidDimensions()
    {
        $solid = new Solid(3, 2, 0);
        new ContainerLevel($solid);
    }

    /**
     * @param $sWidth
     * @param $sLength
     * @param $cWidth
     * @param $cLength
     * @param $expectedDimensions
     * @dataProvider calculateNewOpenAreasWithValidDimensionsData
     */
    public function testCalculateNewOpenAreasWithValidDimensions($sWidth, $sLength, $cWidth, $cLength, $expectedDimensions)
    {
        $solid = new Solid($sWidth, $sLength);
        $containerSolid = new Solid($cWidth, $cLength, 1);
        $container = new ContainerLevel($containerSolid);

        $expectedSolids = [];
        foreach ($expectedDimensions as $expectSolidDimensions) {
            $expectedSolids[] = new Solid($expectSolidDimensions[0], $expectSolidDimensions[1]);
        }

        $this->assertEquals($expectedSolids, $container->calculateNewSpaces($solid, $containerSolid));
    }

    public function calculateNewOpenAreasWithValidDimensionsData()
    {
        return [
            [1, 1, 2, 2, [[2, 1], [1, 1]]],
            [2, 1, 2, 2, [[2, 1]]],
            [2, 2, 2, 2, []],
        ];
    }

    /**
     * @expectedException \InvalidArgumentException
     */
    public function testCalculateNewOpenAreasWithInvalidDimensions()
    {
        $solid = new Solid(3, 1);
        $containerSolid = new Solid(2, 2, 1);
        $container = new ContainerLevel($containerSolid);

        $container->calculateNewSpaces($solid, $containerSolid);
    }

    public function getContentsMaxHeight()
    {
        $container = ContainerLevel::createFromDimensions(5, 1, 5);
        $container->addSolid(new Solid(1, 1, 1));
        $container->addSolid(new Solid(1, 1, 3));
        $container->addSolid(new Solid(1, 1, 2));

        $this->assertEquals(2, $container->getContentsMaxHeight());
    }

    public function testAddToSubcontainers()
    {
        $level = ContainerLevel::createFromDimensions(4, 4, 4);

        // This one goes into a space (not a container)
        $this->assertTrue($level->addSolid(new Solid(4, 3, 2)));

        // This one won't fit into remaining spaces, triggers ContainerLevel::initContainers
        $this->assertFalse($level->addSolid(new Solid(4, 3, 2)));

        // This one should fit into the level's container (generated by ContainerLevel::initContainers)
        $this->assertTrue($level->addSolid(new Solid(4, 1, 1)));

        // This should also fit into the level's container
        $this->assertTrue($level->addSolid(new Solid(4, 1, 1)));

        // This one won't fit into the level's container, which is now full
        $this->assertFalse($level->addSolid(new Solid(4, 1, 1)));
    }

    public function testGetContentsCountSimple()
    {
        $iterations = 5;
        for ($expectedCount = 0; $expectedCount < $iterations; $expectedCount++) {
            $level = ContainerLevel::createFromDimensions(4, 4, 4);

            for ($i = 0; $i < $expectedCount; $i++) {
                $level->addSolid(new Solid(1, 1, 1));
            }
            $this->assertEquals($expectedCount, $level->getContentsCount());
        }
    }

    /**
     * @throws Exception
     */
    public function testGetMultiLevelContentsCount()
    {
        $level = ContainerLevel::createFromDimensions(4, 4, 4);

        $level->addSolid(new Solid(4, 3, 2));
        $level->addSolid(new Solid(4, 3, 2));
        $level->addSolid(new Solid(4, 1, 1));
        $level->addSolid(new Solid(4, 1, 1));
        $level->addSolid(new Solid(4, 1, 1));

        $this->assertEquals(4, $level->getContentsCount());
    }

//    public function testGetKeyOfSmallestViableSpace()
//    {
//        $container = Container::createFromDimensions(3, 3, 1);
//        $container->addSolid(new Solid(2, 1));
//
//        $solid1 = new Solid(2,1);
//        $this->assertEquals(1, $container->getKeyOfSmallestViableSpace($solid1));
//
//        $solid2 = new Solid(1, 1);
//        $this->assertEquals(0, $container->getKeyOfSmallestViableSpace($solid2));
//    }


//    public function testGetContentsCount()
//    {
//        $container = Container::createFromDimensions(10, 10, 10);
//        $container->addSolid(new Solid(2, 2, 2));
//        $container->addSolid(new Solid(2, 2, 2));
//
//        $this->assertEquals(2, $container->getContentsCount());
//    }

}